travis:
  secure:
    BINSTAR_TOKEN: YAiO82HA092bFuj01k4ktLpxfJW12ZzKmt2z40s6mXJwSz7XuF+MviXM69XHSESNd5CyAYvDzjDqbdzpR9fqEFMgCSHEUWGp7mIEYiPkbepO2k9AfTgOrC4YBW5r9i8NDpdJLddUDbYEFC3oMMx+od2z9yAmzE0WfERTA2fBfVtbyd0fW7CHju/c8uf0oygR5xMk9YiN+3q2+iyQ2UEtaNZ6ASdtRVQWPyYn0VMJucwsU/GkqateHNRdeCHeVCvYo/jZkmzWucr6e+NLxm2sTZyiR++17B6n+lZRpNSa1exuTtDZHfqSUn73ThchA3oqxPyfuyF1iWQUv/+WnIMCooDnANmTWRrRoyC6dKo+Vge2YlbTcZ5v3ALf9DiOtNXD9RS3A7Qj0Z58AeMLf/moMIOWwnSeAhIj0ERAqJrCdafGDSExJediuV5mO9I0MlmT0Bkw4nmVj654Zg+n/ugwJ9grcY10zXCYoWWuHTF0+cepV6bMO5gsNtWLtFZWX0VjaB3OT6re+7KmgX09pfU9HMxengVACDg6f00QcmKWIvwRKSMpDuD8vysxDweOOe5ewuePXfG77vsn21AKZoiT7IlN1KRxpL8MQG4RWyXy1e/o1WCHWI5IGBOOlq78zgtSMO8jbdek75HwwqK8kxOJFEyA4lOs47iihInbRhgNjQo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
